name: chatui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.10.0
  firebase_auth: ^4.16.0
  firebase_phone_auth_handler: ^1.0.8
  auto_route: ^7.8.5
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2                  
  build_runner:                   
  


  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/register.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/register.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/register.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/register.png"
flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/register.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
